Ldownload/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("link.urls")),
]

link/urls.py
from django.urls import path
from link.views import *
app_name = 'LIN'

urlpatterns = [
    path('', welcome),
    path('video_download/', show_cli_b, name='show_video'),
    path('download/<resolution>/', done_dow_ur, name='file'),
]

link/models.py
from django.db import models

# Create your models here.

link/views.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse
from pytube import YouTube
import os
import re


# Create your views here.

def welcome(request):
    return render(request, 'main_doc.html')



def is_valid_youtube_url(url):
    # Regular expression to validate YouTube URLs
    # This is a simple example, and you may want to use a more comprehensive regex
    return re.match(r'^https?://(?:www\.)?youtube\.com/watch\?v=\w+', url)

def show_cli_b(request):
    global url
    url = request.GET.get('link')
    #print(url)

    if not url or not is_valid_youtube_url(url):
        error = render(request, 'error.html')
        return HttpResponse(error)
        # return HttpResponse("Invalid or missing YouTube video link.")

    try:
        obj = YouTube(url)

        '''video = obj.streams.filter(progressive=True).all()
        for i in video:
            print(i)'''

        lis = []
        video_resolutions = obj.streams.all()
        #print(video_resolutions)
        for i in video_resolutions:
            lis.append(i.resolution)
        # =======================================================
        # Filter out None values and create a list of resolutions
        resolutions = [res for res in lis if res is not None]
        unique_resolutions = list(set(resolutions))

        # Create a dictionary to map the string resolutions to corresponding numerical values
        resolution_values = {'144p': 144, '240p': 240, '360p': 360,
                              '480p': 480, '720p': 720, '1080p': 1080, '1440p': 1440, '2160p': 2160,}

        # Sort the resolutions in descending order based on their numerical values
        sorted_resolutions = sorted(unique_resolutions, key=lambda x: resolution_values[x], reverse=True)

        # =======================================================

        # -------------------------------------
        link = url.replace("watch?v=", "embed/")        
        try:
            yt = YouTube(link)
            vid_thub = yt.thumbnail_url
            #video_stream = yt.streams.get_highest_resolution()
            #video_url = video_stream.url
        except Exception as e:
            # Handle any errors that might occur during fetching the video URL
            video_url = None
        # ----------------------------------------

        title = obj.title
        time = obj.length
        channel_id = obj.author

        text = {'vid_thub': vid_thub, 'title': title, 'time': time, 'channel_id': channel_id, 'video_res': sorted_resolutions}

        return render(request, 'click_dow.html', text)
    
    except Exception as e:
        # Handle any exceptions that might occur during the process
        return HttpResponse("Error occurred while fetching YouTube video details: " + str(e))



def done_dow_ur(request, resolution):
    obj = YouTube(url)
    homedir = os.path.expanduser('~')
    dirs = homedir + '/Downloads'
    #print('dirs = ', dirs)

    if request.method == "POST":
        #selected_stream = obj.streams.get_by_resolution(resolution)
        selected_stream = obj.streams.filter(res=resolution).first()

        if selected_stream:
            try:
                selected_stream.download(dirs)
                return render(request, 'download_complete.html')
            except Exception as e:
                return render(request, 'download_error.html', {'error_message': str(e)})
        else:
            return render(request, 'download_error.html', {'error_message': 'Selected resolution is not available for this video.'})
    else:
        return render(request, 'download_error.html', {'error_message': 'Invalid request method.'})

link/templates/click_dow.html
{% extends 'main_doc.html' %}

{% block navbarHeader %}

<div class="container">
  <div class="row">
    <div class="col-sm-8 col-md-7 py-4">


      <div class="col-sm-5 col-md-8 py-0">
        <div class="card shadow-sm">
          
          <rect width="100%" height="100%" fill="#55595c"></rect>
          <img src="{{ vid_thub }}" class="bd-placeholder-img card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">{{ title }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <P>{{ channel_id }}</P>
              </div>
              <small class="text-body-secondary">{{ time }}</small>
            </div>
          </div>
        </div>
      </div>


    </div>
    <div class="col-sm-5 p-3 offset-md--1 py-4">
      <table class="table table-bordered">
        <thead">
          <tr>
            <th scope="col">Select resolution</th>
            <th scope="col">Download</th>
          </tr>
        </thead>
        <tbody>
          {% for i in video_res %}
            
            <tr>
              <td>{{ i }}</td>
              
              <td>
                <form action="{% url 'LIN:file' i %}" method="post">
                  {% csrf_token %}
                  <a href="" download="">
                    <button type="submit" class="btn btn-secondary" name="resolution" value="{{ i }}">Download</button>
                  </a>
                </form>
              </td>
            </tr>
            
          {% endfor %}
        </tbody>
      </table>

{% endblock %}

link/templates/download_complete.html
<!-- templates/video_downloader/download_complete.html -->
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <title>Download Complete</title>
</head>
<body>
    <div class="bg-body-tertiary p-5 rounded mt-3">
        <h1>Download Complete</h1>
        <p>Your videos) ' - ' have been downloaded successfully!</p>
    </div>
</body>
</html>

link/templates/download_error.html
<!-- templates/video_downloader/download_error.html -->
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <title>Error</title>
</head>
<body>
    <div class="bg-body-tertiary p-5 rounded mt-3">
        <h1>Error ??</h1>
        <p>Please try again -- </p>
    </div>
</body>
</html>

link/templates/error.html
{% extends 'main_doc.html' %}

{% block error %}

<div id="convert-error" role="alert" class=" btn-lg px-4">
    <div class="container">
        <div class="text-center">
            <div>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-emoji-frown-fill" viewBox="0 0 16 16">
                    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm-2.715 5.933a.5.5 0 0 1-.183-.683A4.498 4.498 0 0 1 8 9.5a4.5 4.5 0 0 1 3.898 2.25.5.5 0 0 1-.866.5A3.498 3.498 0 0 0 8 10.5a3.498 3.498 0 0 0-3.032 1.75.5.5 0 0 1-.683.183zM10 8c-.552 0-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5S10.552 8 10 8z"/>
                  </svg>
                <span class="conver-error-title"></span>Sorry</span>
                <i class="far fa-frown"></i>
            </div> 
            <div class="conver-error-text" style="color: darkred;">The download link was not found</div>
        </div>
    </div>
</div>

{% endblock %}

link/templates/header.html
{% extends 'main.html' %}

{% block header %} 
<header data-bs-theme="dark">
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-down-circle-fill" viewBox="0 0 16 16">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v5.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V4.5z"/>
        </svg>
        <strong>Down_Loader</strong>
      </a>
    </div>
  </div>
</header>
{% endblock %}

link/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'download.css' %}">
    <title>{% block title %}{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <div class="one">
        {% block top %} {% endblock %}

        {% block header %} {% endblock %}

        {% block main_doc %} {% endblock %}


    </div>
</body>
</html>

link/templates/main_doc.html
{% extends 'header.html' %}

{% block main_doc %} 

<main>
  <div class="form_group">
    <form action="{% url 'LIN:show_video' %}" method="get">
      <section class="py-5 text-center container">
        <div class="row py-lg-5">
          <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">YouTube Video Downloader</h1>
            <p class="lead text-body-secondary">Download Youtube video 1080p, 4k, 8k on iPhone Android
            </p>
            <div class="input-group mb-3">
              <input type="text" name="link" placeholder="Paste your video link here" autofocus="autofocus" required="required" id="id_url" class="form-control">
              <span class="input-group-text" id="basic-addon2">
                <button type="submit" data-bs-toggle="collapse" data-bs-target="#navbarHeader" class="btn btn-outline-success" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                Download
                </button>
              </span>
            </div>
            <div>
              {% block error %} {% endblock %}
            </div>
          </div>
      </form>
    </div>
  </section>


  <div class="form_group">
    <div class="album py-lg-5 bg-light">
      <div class="container">
        
        
        <div class="h-100 text-bg-dark rounded-3" id="navbarHeader">
          {% block navbarHeader %} {% endblock %}

        </div>


      </div>
    </div>
  <div class="album py-lg-5 bg-light"></div>
  
</div>

</main>

<footer class="text-body-secondary py-5 card-text fs-5 text-body-secondary">
  <div class="pricing-header p-5 pb-md-5 mx-auto text-center">
    <p class="mb-1">How to Download YouTube Videos in Multiple Formats</p>
    <p class="mb-0"> Identify the YouTube video you want to download. Copy the video's URL from the address bar of your web browser. Visit a reliable YouTube video downloader website.<p> There are several options available, such as Y2Mate, SaveFrom.net, or OnlineVideoConverter.</p> Paste the YouTube video URL into the provided field on the downloader website. Select the desired video format and quality. Most downloader websites offer a range of options, including MP4, AVI, WMV, and more. Additionally, they may offer different quality options, such as 720p, 1080p, or higher.<p>Click on the "Download" or "Convert" button to start the process.</p></p>
  </div>
</footer>


{% endblock %}